[project]
name = "opinionsearch"
version = "0.1.0"
description = "opinions search engine"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.0,<6.0",
    "flagembedding",
    "pgvector>=0.3",
    "psycopg[binary]>=3.1",
    "python-dotenv>=1.0.1",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "pytest-django>=4.8.0",
    "django-debug-toolbar>=4.3.0",
    "black>=24.0.0",
]

[tool.uv.sources]
flagembedding = { git = "https://github.com/FlagOpen/FlagEmbedding.git" }

