# Generated by Django 5.2.17 on 2026-09-09 12:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CreateExtension("postgis"),
        VectorExtension(),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("centroid", pgvector.django.vector.VectorField(dimensions=1024)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Opinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("topic", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "geo_coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Argument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "opinion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arguments",
                        to="opinions.opinion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpinionEmbedding",
            fields=[
                (
                    "vector_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1024)),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="embeddings",
                        to="opinions.cluster",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="opinion",
            name="vector",
            field=models.OneToOneField(
                blank=True,
                db_column="vector_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opinion",
                to="opinions.opinionembedding",
            ),
        ),
        migrations.AddField(
            model_name="opinion",
            name="author",
            field=models.ForeignKey(
                db_column="user_uuid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opinions",
                to="opinions.user",
                to_field="uuid",
            ),
        ),
        migrations.AddIndex(
            model_name="opinionembedding",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="opinion_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
