# Generated by Django 5.2.17 on 2026-09-09 12:27

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opinions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="geo_coordinates",
        ),
        migrations.RemoveField(
            model_name="user",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="opinion",
            name="geo_coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="opinion",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
