# Generated by Django 5.2.17 on 2026-09-09 15:36

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opinions", "0001_initial"),
    ]

    operations = [
        # Remove the old model and its index first
        migrations.RemoveField(
            model_name="opinionembedding",
            name="cluster",
        ),
        migrations.DeleteModel(
            name="OpinionEmbedding",
        ),
        # Now remove the vector FK from opinion
        migrations.RemoveField(
            model_name="opinion",
            name="vector",
        ),
        # Add the new fields
        migrations.AddField(
            model_name="opinion",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opinions",
                to="opinions.cluster",
            ),
        ),
        migrations.AddField(
            model_name="opinion",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
        # Now add the index on the new column
        migrations.AddIndex(
            model_name="opinion",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="opinion_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
