# Generated by Django 5.2.17 on 2026-09-10 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opinions", "0002_remove_opinionembedding_cluster_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission_key_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("access_token", models.CharField(editable=False, max_length=64)),
            ],
        ),
    ]
