# Generated by Django 5.2.17 on 2026-09-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opinions", "0002_remove_opinionembedding_cluster_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opinion",
            name="sentiment",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
