# Generated by Django 5.2.17 on 2026-09-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opinions", "0003_opinion_sentiment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cluster",
            options={"ordering": ["layer", "evoc_id"]},
        ),
        migrations.RemoveField(
            model_name="opinion",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="opinion",
            name="topic",
        ),
        migrations.AddField(
            model_name="cluster",
            name="evoc_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cluster",
            name="exemplar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exemplar_of",
                to="opinions.opinion",
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="label",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="cluster",
            name="layer",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cluster",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="opinions.cluster",
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="opinion",
            name="clusters",
            field=models.ManyToManyField(
                blank=True, related_name="opinions", to="opinions.cluster"
            ),
        ),
        migrations.AddConstraint(
            model_name="cluster",
            constraint=models.UniqueConstraint(
                fields=("layer", "evoc_id"), name="unique_cluster_per_layer"
            ),
        ),
    ]
