# Generated by Django 5.2.17 on 2026-09-10 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opinions", "0003_contribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="publication",
            field=models.CharField(
                choices=[("private", "Private"), ("public", "Public")],
                default="private",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="opinion",
            name="contribution",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opinion",
                to="opinions.contribution",
            ),
        ),
        migrations.AlterField(
            model_name="opinion",
            name="author",
            field=models.ForeignKey(
                blank=True,
                db_column="user_uuid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opinions",
                to="opinions.user",
                to_field="uuid",
            ),
        ),
        # The original topic blank=True alteration changed validation only
        # (no SQL). EVōC removes that field on the sibling migration branch;
        # omit the obsolete alteration so either upgrade order remains valid.
    ]
