# Generated by Django 5.2.17 on 2026-09-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opinions", "0003_opinion_sentiment"),
        ("opinions", "0004_contribution_search"),
    ]

    operations = []
