# Generated by Django 5.2.17 on 2026-09-10 14:03

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opinions", "0005_merge_0003_opinion_sentiment_0004_contribution_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="opinion",
            name="topic_analysis",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="opinion",
            name="topic_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SlugField(max_length=40),
                blank=True,
                default=list,
                editable=False,
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="opinion",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["topic_ids"], name="opinion_topic_ids_gin"
            ),
        ),
    ]
