# Generated by Django 5.2.17 on 2026-09-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opinions", "0004_alter_cluster_options_remove_opinion_cluster_and_more"),
        ("opinions", "0006_opinion_topics"),
    ]

    operations = []
