# Generated by Django 5.2.17 on 2026-09-10 20:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opinions", "0007_merge_frontend_evoc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opinion",
            name="contribution",
        ),
        migrations.AddField(
            model_name="user",
            name="home_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.DeleteModel(
            name="Contribution",
        ),
    ]
